import React, { useEffect, useMemo, useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { CheckCircle2, Edit3, Globe2, History, RotateCcw, Save, ShieldCheck, Sparkles } from 'lucide-react'
import { usePlayerStore } from '@app/store/player.store'
import { useToast } from '@components/ui/Toast'
import { formatRelative } from '@lib/utils'
import { lyricsService } from '@services/lyrics.service'
import type { Song, TranslationLanguage } from '@/types'

interface LyricsPanelProps {
    song: Song
    userId: string
    canEdit: boolean
}

type LyricsTab = 'viewer' | 'editor' | 'proposals' | 'versions'

export const LyricsPanel: React.FC<LyricsPanelProps> = ({ song, userId, canEdit }) => {
    const { success, error: toastError } = useToast()
    const queryClient = useQueryClient()
    const currentSong = usePlayerStore((state) => state.currentSong)
    const currentTime = usePlayerStore((state) => state.currentTime)

    const [activeTab, setActiveTab] = useState<LyricsTab>('viewer')
    const [isEditing, setIsEditing] = useState(false)
    const [draft, setDraft] = useState('')
    const [proposalDraft, setProposalDraft] = useState('')
    const [proposalNote, setProposalNote] = useState('')
    const [selectedLanguage, setSelectedLanguage] = useState<'original' | TranslationLanguage>('original')

    const { data: lyrics, isLoading } = useQuery({
        queryKey: ['song-lyrics', song.id],
        queryFn: () => lyricsService.getLyrics(song.id),
        enabled: !!song.id,
    })

    const { data: proposals } = useQuery({
        queryKey: ['song-lyrics-proposals', song.id],
        queryFn: () => lyricsService.listProposals(song.id),
        enabled: !!song.id,
    })

    const { data: versions } = useQuery({
        queryKey: ['song-lyrics-versions', song.id],
        queryFn: () => lyricsService.listVersions(song.id),
        enabled: !!song.id,
    })

    const { data: translation } = useQuery({
        queryKey: ['song-lyrics-translation', song.id, selectedLanguage],
        queryFn: () => lyricsService.getTranslation(song.id, selectedLanguage as TranslationLanguage),
        enabled: !!song.id && selectedLanguage !== 'original',
    })

    useEffect(() => {
        if (isEditing) return
        setDraft(lyrics?.raw_text ?? '')
    }, [lyrics?.raw_text, isEditing])

    useEffect(() => {
        if (proposalDraft.trim()) return
        setProposalDraft(lyrics?.raw_text ?? lyricsService.buildAutoDraft(song))
    }, [lyrics?.raw_text, proposalDraft, song])

    const saveMutation = useMutation({
        mutationFn: async () => {
            return lyricsService.saveLyrics({
                songId: song.id,
                userId,
                rawText: draft,
                source: 'manual',
                isAutoGenerated: false,
            })
        },
        onSuccess: () => {
            success('Letras guardadas', 'Cambios aplicados correctamente.')
            setIsEditing(false)
            void invalidateLyricsQueries(queryClient, song.id)
        },
        onError: () => {
            toastError('Error', 'No se pudieron guardar las letras.')
        },
    })

    const proposalMutation = useMutation({
        mutationFn: async () => {
            return lyricsService.submitProposal(song.id, userId, proposalDraft, proposalNote)
        },
        onSuccess: () => {
            success('Propuesta enviada', 'El autor puede revisarla y aprobarla.')
            setProposalNote('')
            void queryClient.invalidateQueries({ queryKey: ['song-lyrics-proposals', song.id] })
        },
        onError: () => {
            toastError('Error', 'No se pudo enviar la propuesta.')
        },
    })

    const reviewProposalMutation = useMutation({
        mutationFn: async ({ proposalId, action }: { proposalId: string; action: 'approved' | 'rejected' }) => {
            return lyricsService.reviewProposal(proposalId, userId, action)
        },
        onSuccess: () => {
            success('Revision aplicada')
            void invalidateLyricsQueries(queryClient, song.id)
        },
        onError: () => {
            toastError('Error', 'No se pudo revisar la propuesta.')
        },
    })

    const rollbackMutation = useMutation({
        mutationFn: async (versionId: string) => lyricsService.rollbackToVersion(song.id, versionId, userId),
        onSuccess: () => {
            success('Rollback aplicado', 'Version restaurada correctamente.')
            void invalidateLyricsQueries(queryClient, song.id)
        },
        onError: () => {
            toastError('Error', 'No se pudo restaurar la version.')
        },
    })

    const verifyMutation = useMutation({
        mutationFn: async (verified: boolean) => lyricsService.setVerified(song.id, userId, verified),
        onSuccess: (_, verified) => {
            success(verified ? 'Letra verificada' : 'Verificacion removida')
            void queryClient.invalidateQueries({ queryKey: ['song-lyrics', song.id] })
        },
        onError: () => toastError('Error', 'No se pudo actualizar verificacion.'),
    })

    const translateMutation = useMutation({
        mutationFn: async (language: TranslationLanguage) => {
            const baseText = lyrics?.raw_text ?? ''
            if (!baseText.trim()) throw new Error('empty-lyrics')
            return lyricsService.translateLyrics(song.id, userId, language, baseText)
        },
        onSuccess: (_data, language) => {
            success('Traduccion lista', `Version ${language.toUpperCase()} disponible.`)
            setSelectedLanguage(language)
            void queryClient.invalidateQueries({ queryKey: ['song-lyrics-translation', song.id, language] })
        },
        onError: (err) => {
            if (err instanceof Error && err.message === 'empty-lyrics') {
                toastError('Error', 'Primero necesitas letras originales.')
                return
            }
            toastError('Error', 'No se pudo traducir la letra.')
        },
    })

    const sourceText = selectedLanguage === 'original' ? (lyrics?.raw_text ?? '') : (translation?.raw_text ?? '')

    const renderedLines = useMemo(() => {
        if (selectedLanguage === 'original' && lyrics?.lines && lyrics.lines.length > 0) return lyrics.lines
        if (!sourceText.trim()) return []
        return lyricsService.parseTimedLyrics(song.id, sourceText)
    }, [lyrics?.lines, selectedLanguage, song.id, sourceText])

    const previewLines = useMemo(
        () => lyricsService.parseTimedLyrics(song.id, draft),
        [song.id, draft]
    )

    const activeLineIndex = useMemo(() => {
        if (currentSong?.id !== song.id || renderedLines.length === 0) return -1

        return renderedLines.findIndex((line, index) => {
            const start = line.start_seconds
            if (start == null) return false
            const next = renderedLines[index + 1]?.start_seconds ?? null
            const end = line.end_seconds ?? next ?? start + 4
            return currentTime >= start && currentTime < end
        })
    }, [currentSong?.id, currentTime, renderedLines, song.id])

    if (isLoading) {
        return <div className="card p-4 text-sm text-gray-400">Cargando letras...</div>
    }

    return (
        <section className="card p-4 space-y-4">
            <div className="flex flex-wrap items-center justify-between gap-2">
                <div>
                    <h2 className="text-base font-semibold text-white">Letras</h2>
                    <p className="text-xs text-gray-400">
                        {lyrics?.is_verified ? 'Verificada por autor' : 'No verificada'} · {lyrics?.is_auto_generated ? 'ASR auto' : 'Manual'}
                    </p>
                </div>
                <div className="flex flex-wrap items-center gap-2">
                    <select
                        value={selectedLanguage}
                        onChange={(event) => setSelectedLanguage(event.target.value as 'original' | TranslationLanguage)}
                        className="bg-surface-700 border border-surface-500 text-xs rounded-lg px-2.5 py-2"
                    >
                        <option value="original">Original</option>
                        <option value="es">ES</option>
                        <option value="en">EN</option>
                    </select>

                    <button
                        type="button"
                        onClick={() => translateMutation.mutate(selectedLanguage === 'en' ? 'es' : 'en')}
                        className="btn-secondary px-3 py-2 text-xs"
                        disabled={translateMutation.isPending}
                    >
                        <Globe2 className="w-3.5 h-3.5" />
                        Traducir
                    </button>

                    {canEdit ? (
                        <button
                            type="button"
                            onClick={() => verifyMutation.mutate(!(lyrics?.is_verified ?? false))}
                            className={`btn-secondary px-3 py-2 text-xs ${(lyrics?.is_verified ?? false) ? 'border-emerald-400/50 text-emerald-300' : ''}`}
                            disabled={verifyMutation.isPending}
                        >
                            <ShieldCheck className="w-3.5 h-3.5" />
                            {(lyrics?.is_verified ?? false) ? 'Quitar verificacion' : 'Verificar'}
                        </button>
                    ) : null}
                </div>
            </div>

            <div className="flex gap-2 overflow-x-auto no-scrollbar">
                <TabButton active={activeTab === 'viewer'} onClick={() => setActiveTab('viewer')} label="Karaoke" />
                <TabButton active={activeTab === 'editor'} onClick={() => setActiveTab('editor')} label="Editor" />
                <TabButton active={activeTab === 'proposals'} onClick={() => setActiveTab('proposals')} label="Propuestas" />
                <TabButton active={activeTab === 'versions'} onClick={() => setActiveTab('versions')} label="Versiones" />
            </div>

            {activeTab === 'viewer' ? (
                renderedLines.length === 0 ? (
                    <div className="rounded-xl border border-dashed border-surface-400 p-6 text-center text-sm text-gray-400">
                        No hay letras todavia para esta cancion.
                    </div>
                ) : (
                    <div className="max-h-[360px] overflow-y-auto no-scrollbar pr-1 space-y-1.5">
                        {renderedLines.map((line, idx) => (
                            <p
                                key={line.id ?? `${line.song_id}-${line.line_index}-${idx}`}
                                className={`rounded-lg px-2.5 py-1.5 text-sm transition-colors ${
                                    idx === activeLineIndex
                                        ? 'bg-brand-500/20 text-brand-100 border border-brand-400/40'
                                        : 'text-gray-200'
                                }`}
                            >
                                {line.content}
                            </p>
                        ))}
                    </div>
                )
            ) : null}

            {activeTab === 'editor' ? (
                canEdit ? (
                    <div className="space-y-3">
                        <div className="flex items-center gap-2">
                            <button
                                type="button"
                                onClick={() => {
                                    const generated = lyricsService.buildAutoDraft(song)
                                    setDraft(generated)
                                    setIsEditing(true)
                                }}
                                className="btn-secondary px-3 py-2 text-xs"
                            >
                                <Sparkles className="w-3.5 h-3.5" />
                                Generar base
                            </button>
                            <button
                                type="button"
                                onClick={() => setIsEditing((prev) => !prev)}
                                className="btn-secondary px-3 py-2 text-xs"
                            >
                                <Edit3 className="w-3.5 h-3.5" />
                                {isEditing ? 'Cerrar editor' : 'Editar'}
                            </button>
                        </div>

                        {isEditing ? (
                            <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
                                <div className="space-y-2">
                                    <textarea
                                        value={draft}
                                        onChange={(event) => setDraft(event.target.value)}
                                        rows={14}
                                        className="input min-h-[280px] font-mono text-xs leading-6"
                                        placeholder="[00:00.00] Primera linea"
                                    />
                                    <div className="flex items-center justify-between gap-2">
                                        <p className="text-[11px] text-gray-500">Formato: [mm:ss.xx] texto</p>
                                        <button
                                            type="button"
                                            onClick={() => saveMutation.mutate()}
                                            disabled={saveMutation.isPending || !draft.trim()}
                                            className="btn-primary px-3 py-2 text-xs"
                                        >
                                            <Save className="w-3.5 h-3.5" /> Guardar
                                        </button>
                                    </div>
                                </div>

                                <div className="rounded-xl border border-surface-500 bg-surface-700/40 p-2.5">
                                    <p className="text-xs text-gray-400 mb-2">Vista previa en tiempo real</p>
                                    <div className="max-h-[300px] overflow-y-auto no-scrollbar space-y-1.5 pr-1">
                                        {previewLines.map((line, idx) => {
                                            const isActivePreview = activeLineIndex === idx
                                            return (
                                                <p
                                                    key={line.id ?? `${idx}`}
                                                    className={`rounded-md px-2 py-1.5 text-sm ${
                                                        isActivePreview ? 'bg-brand-500/20 text-brand-100' : 'text-gray-200'
                                                    }`}
                                                >
                                                    {line.content}
                                                </p>
                                            )
                                        })}
                                    </div>
                                </div>
                            </div>
                        ) : null}
                    </div>
                ) : (
                    <div className="space-y-3">
                        <p className="text-sm text-gray-300">No eres el autor. Puedes enviar una propuesta de edicion.</p>
                        <textarea
                            value={proposalDraft}
                            onChange={(event) => setProposalDraft(event.target.value)}
                            rows={12}
                            className="input min-h-[220px] font-mono text-xs leading-6"
                            placeholder="Propone aqui una version mejorada"
                        />
                        <input
                            value={proposalNote}
                            onChange={(event) => setProposalNote(event.target.value)}
                            className="input"
                            placeholder="Nota para el autor (opcional)"
                        />
                        <button
                            type="button"
                            onClick={() => proposalMutation.mutate()}
                            disabled={proposalMutation.isPending || !proposalDraft.trim()}
                            className="btn-primary px-3 py-2 text-xs"
                        >
                            <CheckCircle2 className="w-3.5 h-3.5" /> Enviar propuesta
                        </button>
                    </div>
                )
            ) : null}

            {activeTab === 'proposals' ? (
                <div className="space-y-2.5">
                    {(proposals ?? []).length === 0 ? (
                        <div className="rounded-xl border border-dashed border-surface-400 p-5 text-sm text-gray-400 text-center">
                            No hay propuestas pendientes.
                        </div>
                    ) : (
                        (proposals ?? []).map((proposal) => (
                            <article key={proposal.id} className="rounded-xl border border-surface-500 bg-surface-700/40 p-3 space-y-2">
                                <div className="flex items-center justify-between gap-2">
                                    <p className="text-xs text-gray-400">
                                        {proposal.proposer?.display_name ?? 'Miembro'} · {formatRelative(proposal.created_at)}
                                    </p>
                                    <span className={`text-[11px] px-2 py-1 rounded-full border ${
                                        proposal.status === 'approved'
                                            ? 'border-emerald-500/40 text-emerald-300'
                                            : proposal.status === 'rejected'
                                                ? 'border-red-500/40 text-red-300'
                                                : 'border-amber-500/40 text-amber-300'
                                    }`}>
                                        {proposal.status}
                                    </span>
                                </div>
                                {proposal.note ? <p className="text-xs text-gray-300">{proposal.note}</p> : null}
                                <pre className="whitespace-pre-wrap text-xs text-gray-200 bg-surface-800/70 rounded-lg p-2 max-h-40 overflow-y-auto">{proposal.proposed_raw_text}</pre>

                                {canEdit && proposal.status === 'pending' ? (
                                    <div className="flex items-center gap-2">
                                        <button
                                            type="button"
                                            onClick={() => reviewProposalMutation.mutate({ proposalId: proposal.id, action: 'approved' })}
                                            className="btn-primary px-3 py-2 text-xs"
                                        >
                                            Aprobar
                                        </button>
                                        <button
                                            type="button"
                                            onClick={() => reviewProposalMutation.mutate({ proposalId: proposal.id, action: 'rejected' })}
                                            className="btn-secondary px-3 py-2 text-xs"
                                        >
                                            Rechazar
                                        </button>
                                    </div>
                                ) : null}
                            </article>
                        ))
                    )}
                </div>
            ) : null}

            {activeTab === 'versions' ? (
                <div className="space-y-2.5">
                    {(versions ?? []).length === 0 ? (
                        <div className="rounded-xl border border-dashed border-surface-400 p-5 text-sm text-gray-400 text-center">
                            Historial vacio por ahora.
                        </div>
                    ) : (
                        (versions ?? []).map((version) => (
                            <article key={version.id} className="rounded-xl border border-surface-500 bg-surface-700/40 p-3">
                                <div className="flex items-center justify-between gap-2">
                                    <div className="flex items-center gap-2 text-xs text-gray-300">
                                        <History className="w-3.5 h-3.5" />
                                        v{version.version_number} · {formatRelative(version.created_at)}
                                    </div>
                                    {canEdit ? (
                                        <button
                                            type="button"
                                            onClick={() => rollbackMutation.mutate(version.id)}
                                            className="btn-secondary px-3 py-1.5 text-xs"
                                            disabled={rollbackMutation.isPending}
                                        >
                                            <RotateCcw className="w-3.5 h-3.5" /> Rollback
                                        </button>
                                    ) : null}
                                </div>
                                <pre className="whitespace-pre-wrap text-xs text-gray-200 bg-surface-800/70 rounded-lg p-2 mt-2 max-h-36 overflow-y-auto">{version.raw_text}</pre>
                            </article>
                        ))
                    )}
                </div>
            ) : null}
        </section>
    )
}

function TabButton({ active, onClick, label }: { active: boolean; onClick: () => void; label: string }) {
    return (
        <button
            type="button"
            onClick={onClick}
            className={`px-3 py-1.5 text-xs rounded-full border whitespace-nowrap transition-colors ${
                active
                    ? 'bg-brand-500/20 text-brand-100 border-brand-400/50'
                    : 'bg-surface-700 text-gray-300 border-surface-500'
            }`}
        >
            {label}
        </button>
    )
}

async function invalidateLyricsQueries(queryClient: ReturnType<typeof useQueryClient>, songId: string): Promise<void> {
    await Promise.all([
        queryClient.invalidateQueries({ queryKey: ['song-lyrics', songId] }),
        queryClient.invalidateQueries({ queryKey: ['song-lyrics-proposals', songId] }),
        queryClient.invalidateQueries({ queryKey: ['song-lyrics-versions', songId] }),
        queryClient.invalidateQueries({ queryKey: ['song-lyrics-translation', songId] }),
    ])
}
