import { supabase } from '@lib/supabase/client'
import { asrService } from '@services/asr.service'
import { groupActivityService } from '@services/group-activity.service'
import type {
    LyricsProposalStatus,
    LyricsSource,
    Song,
    SongLyricLine,
    SongLyrics,
    SongLyricsProposal,
    SongLyricsTranslation,
    SongLyricsVersion,
    TranslationLanguage,
} from '@/types'

const STORAGE_KEYS = {
    lyrics: 'appden:lyrics:fallback:v2',
    versions: 'appden:lyrics:versions:fallback:v1',
    proposals: 'appden:lyrics:proposals:fallback:v1',
    translations: 'appden:lyrics:translations:fallback:v1',
} as const

type SaveLyricsInput = {
    songId: string
    userId: string
    rawText: string
    language?: string
    source?: LyricsSource
    isAutoGenerated?: boolean
    confidence?: number | null
    lines?: SongLyricLine[]
    suppressActivity?: boolean
}

type AutoTranscribeInput = {
    song: Song
    audioFile: File
    userId: string
}

type LyricsFallbackStore = Record<string, { lyrics: SongLyrics; lines: SongLyricLine[] }>
type VersionsFallbackStore = Record<string, SongLyricsVersion[]>
type TranslationsFallbackStore = Record<string, SongLyricsTranslation[]>

type ProposalsFallbackStore = SongLyricsProposal[]

export const lyricsService = {
    async getLyrics(songId: string): Promise<SongLyrics | null> {
        const { data: lyricsRow, error: lyricsError } = await supabase
            .from('song_lyrics')
            .select('*')
            .eq('song_id', songId)
            .maybeSingle()

        if (lyricsError) {
            if (isMissingRelationError(lyricsError)) {
                return readFallbackLyrics(songId)
            }
            throw lyricsError
        }

        if (!lyricsRow) return null

        const { data: linesRows, error: linesError } = await supabase
            .from('song_lyric_lines')
            .select('*')
            .eq('song_id', songId)
            .order('line_index', { ascending: true })

        if (linesError && !isMissingRelationError(linesError)) {
            throw linesError
        }

        return {
            ...(lyricsRow as SongLyrics),
            lines: (linesRows ?? []) as SongLyricLine[],
        }
    },

    async saveLyrics(input: SaveLyricsInput): Promise<SongLyrics> {
        const parsedLines = input.lines ?? parseTimedLyrics(input.songId, input.rawText)
        await snapshotVersion(input)

        const payload = {
            song_id: input.songId,
            raw_text: input.rawText.trim(),
            language: input.language ?? 'es',
            source: input.source ?? 'manual',
            is_auto_generated: input.isAutoGenerated ?? false,
            confidence: input.confidence ?? null,
            updated_by: input.userId,
            is_verified: false,
            verified_by: null,
            verified_at: null,
        }

        const { data: lyricsRow, error: lyricsError } = await supabase
            .from('song_lyrics')
            .upsert(payload, { onConflict: 'song_id' })
            .select('*')
            .single()

        if (lyricsError) {
            if (isMissingRelationError(lyricsError)) {
                const saved = writeFallbackLyrics(input, parsedLines)
                if (!input.suppressActivity) {
                    await logLyricsActivity(saved.song_id, input.userId, 'lyrics_updated')
                }
                return saved
            }
            throw lyricsError
        }

        const { error: deleteLinesError } = await supabase
            .from('song_lyric_lines')
            .delete()
            .eq('song_id', input.songId)

        if (deleteLinesError && !isMissingRelationError(deleteLinesError)) {
            throw deleteLinesError
        }

        if (parsedLines.length > 0) {
            const linesPayload = parsedLines.map((line, idx) => ({
                song_id: input.songId,
                line_index: idx,
                content: line.content,
                start_seconds: line.start_seconds,
                end_seconds: line.end_seconds,
            }))

            const { error: insertLinesError } = await supabase
                .from('song_lyric_lines')
                .insert(linesPayload)

            if (insertLinesError && !isMissingRelationError(insertLinesError)) {
                throw insertLinesError
            }
        }

        const saved: SongLyrics = {
            ...(lyricsRow as SongLyrics),
            lines: parsedLines,
        }

        await appendVersion(saved, input.userId)

        if (!input.suppressActivity) {
            await logLyricsActivity(saved.song_id, input.userId, 'lyrics_updated')
        }

        return saved
    },

    async autoTranscribeOnUpload(input: AutoTranscribeInput): Promise<SongLyrics> {
        const transcript = await asrService.transcribeOnUpload(input.audioFile, {
            id: input.song.id,
            title: input.song.title,
            artist_name: input.song.artist_name,
        })

        return this.saveLyrics({
            songId: input.song.id,
            userId: input.userId,
            rawText: transcript.rawText,
            language: transcript.language,
            source: 'auto',
            isAutoGenerated: true,
            confidence: transcript.confidence,
            lines: transcript.lines,
            suppressActivity: true,
        })
    },

    async listVersions(songId: string): Promise<SongLyricsVersion[]> {
        const { data, error } = await supabase
            .from('song_lyrics_versions')
            .select('*')
            .eq('song_id', songId)
            .order('version_number', { ascending: false })

        if (error) {
            if (isMissingRelationError(error)) {
                return readFallbackVersions(songId)
            }
            throw error
        }

        return (data ?? []) as SongLyricsVersion[]
    },

    async rollbackToVersion(songId: string, versionId: string, userId: string): Promise<SongLyrics> {
        const { data, error } = await supabase
            .from('song_lyrics_versions')
            .select('*')
            .eq('song_id', songId)
            .eq('id', versionId)
            .maybeSingle()

        if (error) {
            if (isMissingRelationError(error)) {
                const fallback = readFallbackVersions(songId).find((item) => item.id === versionId)
                if (!fallback) throw new Error('Version no encontrada.')
                return this.saveLyrics({
                    songId,
                    userId,
                    rawText: fallback.raw_text,
                    language: fallback.language,
                    source: fallback.source,
                    isAutoGenerated: fallback.is_auto_generated,
                    confidence: fallback.confidence,
                })
            }
            throw error
        }

        if (!data) throw new Error('Version no encontrada.')

        const version = data as SongLyricsVersion
        return this.saveLyrics({
            songId,
            userId,
            rawText: version.raw_text,
            language: version.language,
            source: version.source,
            isAutoGenerated: version.is_auto_generated,
            confidence: version.confidence,
        })
    },

    async submitProposal(songId: string, userId: string, proposedRawText: string, note?: string): Promise<SongLyricsProposal> {
        const payload = {
            song_id: songId,
            proposed_by: userId,
            proposed_raw_text: proposedRawText.trim(),
            note: note?.trim() || null,
            status: 'pending' as LyricsProposalStatus,
        }

        const { data, error } = await supabase
            .from('song_lyrics_proposals')
            .insert(payload)
            .select('*, proposer:profiles(id, display_name, avatar_url)')
            .single()

        if (error) {
            if (isMissingRelationError(error)) {
                const proposal = writeFallbackProposal(payload)
                await logLyricsActivity(songId, userId, 'lyrics_proposed')
                return proposal
            }
            throw error
        }

        await logLyricsActivity(songId, userId, 'lyrics_proposed')
        return data as SongLyricsProposal
    },

    async listProposals(songId: string): Promise<SongLyricsProposal[]> {
        const { data, error } = await supabase
            .from('song_lyrics_proposals')
            .select('*, proposer:profiles(id, display_name, avatar_url)')
            .eq('song_id', songId)
            .order('created_at', { ascending: false })

        if (error) {
            if (isMissingRelationError(error)) {
                return readFallbackProposals(songId)
            }
            throw error
        }

        return (data ?? []) as SongLyricsProposal[]
    },

    async reviewProposal(
        proposalId: string,
        reviewerId: string,
        action: Extract<LyricsProposalStatus, 'approved' | 'rejected'>
    ): Promise<void> {
        const { data: proposal, error: proposalError } = await supabase
            .from('song_lyrics_proposals')
            .select('*')
            .eq('id', proposalId)
            .maybeSingle()

        if (proposalError) {
            if (isMissingRelationError(proposalError)) {
                reviewFallbackProposal(proposalId, reviewerId, action)
                return
            }
            throw proposalError
        }

        if (!proposal) throw new Error('Propuesta no encontrada.')

        const { error: reviewError } = await supabase
            .from('song_lyrics_proposals')
            .update({
                status: action,
                reviewed_by: reviewerId,
                reviewed_at: new Date().toISOString(),
            })
            .eq('id', proposalId)

        if (reviewError) throw reviewError

        if (action === 'approved') {
            await this.saveLyrics({
                songId: proposal.song_id as string,
                userId: reviewerId,
                rawText: proposal.proposed_raw_text as string,
                source: 'manual',
                isAutoGenerated: false,
            })
        }
    },

    async setVerified(songId: string, userId: string, verified: boolean): Promise<void> {
        const payload = {
            is_verified: verified,
            verified_by: verified ? userId : null,
            verified_at: verified ? new Date().toISOString() : null,
            updated_by: userId,
        }

        const { error } = await supabase
            .from('song_lyrics')
            .update(payload)
            .eq('song_id', songId)

        if (error) {
            if (isMissingRelationError(error)) {
                const fallback = readFallbackLyrics(songId)
                if (!fallback) return
                const store = readLyricsFallbackStore()
                store[songId] = {
                    lyrics: {
                        ...fallback,
                        is_verified: verified,
                        verified_by: verified ? userId : null,
                        verified_at: verified ? new Date().toISOString() : null,
                        updated_by: userId,
                        updated_at: new Date().toISOString(),
                    },
                    lines: fallback.lines ?? [],
                }
                writeLyricsFallbackStore(store)
                return
            }
            throw error
        }

        await logLyricsActivity(songId, userId, 'lyrics_verified', { verified })
    },

    async getTranslation(songId: string, language: TranslationLanguage): Promise<SongLyricsTranslation | null> {
        const { data, error } = await supabase
            .from('song_lyrics_translations')
            .select('*')
            .eq('song_id', songId)
            .eq('language', language)
            .maybeSingle()

        if (error) {
            if (isMissingRelationError(error)) {
                const entries = readFallbackTranslations(songId)
                return entries.find((entry) => entry.language === language) ?? null
            }
            throw error
        }

        return (data as SongLyricsTranslation | null) ?? null
    },

    async translateLyrics(
        songId: string,
        userId: string,
        targetLanguage: TranslationLanguage,
        baseRawText: string
    ): Promise<SongLyricsTranslation> {
        const translated = await translateText(baseRawText, targetLanguage)

        const payload = {
            song_id: songId,
            language: targetLanguage,
            raw_text: translated,
            source: 'machine' as const,
            updated_by: userId,
        }

        const { data, error } = await supabase
            .from('song_lyrics_translations')
            .upsert(payload, { onConflict: 'song_id,language' })
            .select('*')
            .single()

        if (error) {
            if (isMissingRelationError(error)) {
                return upsertFallbackTranslation(payload)
            }
            throw error
        }

        return data as SongLyricsTranslation
    },

    buildAutoDraft(song: Pick<Song, 'title' | 'artist_name'>): string {
        const title = song.title.trim() || 'New song'
        const artist = song.artist_name.trim() || 'Artist'
        const lines = [
            `[00:00.00] ${title}`,
            `[00:08.00] ${artist}`,
            '[00:16.00] Verse 1 - write exact lyric line',
            '[00:24.00] Verse 1 - continue',
            '[00:32.00] Pre-chorus',
            '[00:40.00] Chorus',
            '[00:48.00] Chorus',
            '[00:56.00] Verse 2',
            '[01:04.00] Pre-chorus',
            '[01:12.00] Chorus',
            '[01:20.00] Bridge',
            '[01:28.00] Outro',
        ]
        return lines.join('\n')
    },

    parseTimedLyrics(songId: string, rawText: string): SongLyricLine[] {
        return parseTimedLyrics(songId, rawText)
    },
}

async function snapshotVersion(input: SaveLyricsInput): Promise<void> {
    const existing = await lyricsService.getLyrics(input.songId)
    if (!existing) return

    if (existing.raw_text.trim() === input.rawText.trim()) return

    await appendVersion(existing, input.userId)
}

async function appendVersion(lyrics: SongLyrics, createdBy: string): Promise<void> {
    const { data: latest, error: latestError } = await supabase
        .from('song_lyrics_versions')
        .select('version_number')
        .eq('song_id', lyrics.song_id)
        .order('version_number', { ascending: false })
        .limit(1)
        .maybeSingle()

    const nextVersion = ((latest?.version_number as number | undefined) ?? 0) + 1

    const payload = {
        song_id: lyrics.song_id,
        version_number: nextVersion,
        raw_text: lyrics.raw_text,
        language: lyrics.language,
        source: lyrics.source,
        is_auto_generated: lyrics.is_auto_generated,
        confidence: lyrics.confidence,
        created_by: createdBy,
    }

    const { error } = await supabase
        .from('song_lyrics_versions')
        .insert(payload)

    if (error) {
        if (isMissingRelationError(error) || isMissingRelationError(latestError)) {
            appendFallbackVersion(lyrics, createdBy)
            return
        }
        throw error
    }
}

function parseTimedLyrics(songId: string, rawText: string): SongLyricLine[] {
    const rows = rawText
        .split('\n')
        .map((line) => line.trim())
        .filter(Boolean)

    if (rows.length === 0) return []

    const timedRegex = /^\[(\d{1,2}):(\d{2})(?:\.(\d{1,3}))?\]\s*(.+)$/
    const parsed = rows.map((row, index) => {
        const match = row.match(timedRegex)
        if (!match) {
            return {
                id: crypto.randomUUID(),
                song_id: songId,
                line_index: index,
                content: row,
                start_seconds: null,
                end_seconds: null,
            } satisfies SongLyricLine
        }

        const min = Number(match[1] ?? 0)
        const sec = Number(match[2] ?? 0)
        const msRaw = match[3] ?? '0'
        const ms = Number(msRaw.padEnd(3, '0'))
        const content = match[4]?.trim() ?? ''

        return {
            id: crypto.randomUUID(),
            song_id: songId,
            line_index: index,
            content,
            start_seconds: min * 60 + sec + ms / 1000,
            end_seconds: null,
        } satisfies SongLyricLine
    })

    const hasTimedRows = parsed.some((row) => row.start_seconds != null)
    if (!hasTimedRows) {
        return parsed.map((line, idx) => ({
            ...line,
            start_seconds: idx * 4,
            end_seconds: (idx + 1) * 4 - 0.1,
        }))
    }

    return parsed.map((line, idx) => {
        const currentStart = line.start_seconds
        if (currentStart == null) return line
        const nextTimed = parsed.slice(idx + 1).find((item) => item.start_seconds != null)
        const nextStart = nextTimed?.start_seconds ?? null
        return {
            ...line,
            end_seconds: nextStart != null ? Math.max(currentStart, nextStart - 0.05) : null,
        }
    })
}

async function translateText(rawText: string, targetLanguage: TranslationLanguage): Promise<string> {
    const endpoint = import.meta.env.VITE_LYRICS_TRANSLATE_ENDPOINT as string | undefined
    if (endpoint) {
        try {
            const response = await fetch(endpoint, {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({ text: rawText, targetLanguage }),
            })
            if (response.ok) {
                const payload = (await response.json()) as { text?: string }
                if (payload.text?.trim()) return payload.text.trim()
            }
        } catch {
            // Fall back to local translation mode.
        }
    }

    const lines = rawText.split('\n')
    if (targetLanguage === 'en') {
        return lines
            .map((line) => line.replace('Estribillo', 'Chorus').replace('Verso', 'Verse').replace('Puente', 'Bridge'))
            .join('\n')
    }

    return lines
        .map((line) => line.replace('Chorus', 'Estribillo').replace('Verse', 'Verso').replace('Bridge', 'Puente'))
        .join('\n')
}

async function logLyricsActivity(
    songId: string,
    actorId: string,
    actionType: 'lyrics_updated' | 'lyrics_proposed' | 'lyrics_verified',
    payload?: Record<string, unknown>
): Promise<void> {
    const groupId = await groupActivityService.resolveSongGroupId(songId)
    if (!groupId) return
    await groupActivityService.create({
        groupId,
        actorId,
        actionType,
        songId,
        payload,
    })
}

function isMissingRelationError(error: unknown): boolean {
    if (!error || typeof error !== 'object') return false
    const anyError = error as { code?: string; message?: string; details?: string }
    const raw = `${anyError.code ?? ''} ${anyError.message ?? ''} ${anyError.details ?? ''}`.toLowerCase()
    return raw.includes('42p01') || raw.includes('pgrst205') || raw.includes('does not exist')
}

function readJson<T>(key: string, fallback: T): T {
    if (typeof window === 'undefined') return fallback
    try {
        const raw = window.localStorage.getItem(key)
        if (!raw) return fallback
        return JSON.parse(raw) as T
    } catch {
        return fallback
    }
}

function writeJson<T>(key: string, value: T): void {
    if (typeof window === 'undefined') return
    try {
        window.localStorage.setItem(key, JSON.stringify(value))
    } catch {
        // Ignore storage quota restrictions.
    }
}

function readLyricsFallbackStore(): LyricsFallbackStore {
    return readJson<LyricsFallbackStore>(STORAGE_KEYS.lyrics, {})
}

function writeLyricsFallbackStore(store: LyricsFallbackStore): void {
    writeJson(STORAGE_KEYS.lyrics, store)
}

function readFallbackLyrics(songId: string): SongLyrics | null {
    const store = readLyricsFallbackStore()
    const entry = store[songId]
    if (!entry) return null
    return {
        ...entry.lyrics,
        lines: entry.lines,
    }
}

function writeFallbackLyrics(input: SaveLyricsInput, lines: SongLyricLine[]): SongLyrics {
    const store = readLyricsFallbackStore()
    const existing = store[input.songId]
    const now = new Date().toISOString()

    const lyrics: SongLyrics = {
        id: existing?.lyrics.id ?? crypto.randomUUID(),
        song_id: input.songId,
        raw_text: input.rawText.trim(),
        language: input.language ?? 'es',
        source: input.source ?? 'manual',
        is_auto_generated: input.isAutoGenerated ?? false,
        confidence: input.confidence ?? null,
        is_verified: false,
        verified_by: null,
        verified_at: null,
        updated_by: input.userId,
        created_at: existing?.lyrics.created_at ?? now,
        updated_at: now,
        lines,
    }

    store[input.songId] = { lyrics, lines }
    writeLyricsFallbackStore(store)
    appendFallbackVersion(lyrics, input.userId)
    return lyrics
}

function readFallbackVersions(songId: string): SongLyricsVersion[] {
    const store = readJson<VersionsFallbackStore>(STORAGE_KEYS.versions, {})
    return store[songId] ?? []
}

function appendFallbackVersion(lyrics: SongLyrics, createdBy: string): void {
    const store = readJson<VersionsFallbackStore>(STORAGE_KEYS.versions, {})
    const current = store[lyrics.song_id] ?? []
    const nextVersion = ((current[0]?.version_number ?? 0) + 1)

    const version: SongLyricsVersion = {
        id: crypto.randomUUID(),
        song_id: lyrics.song_id,
        version_number: nextVersion,
        raw_text: lyrics.raw_text,
        language: lyrics.language,
        source: lyrics.source,
        is_auto_generated: lyrics.is_auto_generated,
        confidence: lyrics.confidence,
        created_by: createdBy,
        created_at: new Date().toISOString(),
    }

    store[lyrics.song_id] = [version, ...current].slice(0, 100)
    writeJson(STORAGE_KEYS.versions, store)
}

function readFallbackProposals(songId: string): SongLyricsProposal[] {
    const all = readJson<ProposalsFallbackStore>(STORAGE_KEYS.proposals, [])
    return all.filter((item) => item.song_id === songId).sort((a, b) => b.created_at.localeCompare(a.created_at))
}

function writeFallbackProposal(payload: {
    song_id: string
    proposed_by: string
    proposed_raw_text: string
    note: string | null
    status: LyricsProposalStatus
}): SongLyricsProposal {
    const all = readJson<ProposalsFallbackStore>(STORAGE_KEYS.proposals, [])
    const proposal: SongLyricsProposal = {
        id: crypto.randomUUID(),
        song_id: payload.song_id,
        proposed_by: payload.proposed_by,
        proposed_raw_text: payload.proposed_raw_text,
        note: payload.note,
        status: payload.status,
        reviewed_by: null,
        reviewed_at: null,
        created_at: new Date().toISOString(),
    }

    writeJson(STORAGE_KEYS.proposals, [proposal, ...all].slice(0, 500))
    return proposal
}

function reviewFallbackProposal(
    proposalId: string,
    reviewerId: string,
    action: Extract<LyricsProposalStatus, 'approved' | 'rejected'>
): void {
    const all = readJson<ProposalsFallbackStore>(STORAGE_KEYS.proposals, [])
    const next = all.map((item) => {
        if (item.id !== proposalId) return item
        return {
            ...item,
            status: action,
            reviewed_by: reviewerId,
            reviewed_at: new Date().toISOString(),
        }
    })
    writeJson(STORAGE_KEYS.proposals, next)
}

function readFallbackTranslations(songId: string): SongLyricsTranslation[] {
    const store = readJson<TranslationsFallbackStore>(STORAGE_KEYS.translations, {})
    return store[songId] ?? []
}

function upsertFallbackTranslation(payload: {
    song_id: string
    language: TranslationLanguage
    raw_text: string
    source: 'machine' | 'manual'
    updated_by: string
}): SongLyricsTranslation {
    const store = readJson<TranslationsFallbackStore>(STORAGE_KEYS.translations, {})
    const current = store[payload.song_id] ?? []
    const existing = current.find((item) => item.language === payload.language)
    const now = new Date().toISOString()

    const nextItem: SongLyricsTranslation = {
        id: existing?.id ?? crypto.randomUUID(),
        song_id: payload.song_id,
        language: payload.language,
        raw_text: payload.raw_text,
        source: payload.source,
        updated_by: payload.updated_by,
        created_at: existing?.created_at ?? now,
        updated_at: now,
    }

    const filtered = current.filter((item) => item.language !== payload.language)
    store[payload.song_id] = [nextItem, ...filtered]
    writeJson(STORAGE_KEYS.translations, store)
    return nextItem
}
